
SELECT COUNTRY_NAME
FROM COUNTRIES;

SELECT JOB_TITLE
FROM JOBS;


SELECT MANAGER_ID
FROM EMPLOYEES;


SELECT LOCATION_ID, ( STREET_ADDRESS || ',' || CITY || ',' || STATE_PROVINCE || ',' || POSTAL_CODE ) ADDRESS
FROM LOCATIONS;

